"""Add source_port and target_port to connections table

Revision ID: 2c3ee6d2cc73
Revises: 59647392d6e9
Create Date: 2025-04-11 14:29:59.967169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c3ee6d2cc73'
down_revision: Union[str, None] = '59647392d6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('source_port', sa.String(length=255), nullable=True))
    op.add_column('connections', sa.Column('target_port', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_connections_source_port'), 'connections', ['source_port'], unique=False)
    op.create_index(op.f('ix_connections_target_port'), 'connections', ['target_port'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connections_target_port'), table_name='connections')
    op.drop_index(op.f('ix_connections_source_port'), table_name='connections')
    op.drop_column('connections', 'target_port')
    op.drop_column('connections', 'source_port')
    # ### end Alembic commands ###