"""Add MachineModel, Component, Connection tables

Revision ID: 59647392d6e9
Revises: 5822eba24f5c
Create Date: 2025-04-11 10:58:00.610180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59647392d6e9'
down_revision: Union[str, None] = '5822eba24f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_models_id'), 'machine_models', ['id'], unique=False)
    op.create_index(op.f('ix_machine_models_name'), 'machine_models', ['name'], unique=False)
    op.create_index(op.f('ix_machine_models_project_id'), 'machine_models', ['project_id'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('machine_model_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_id'), 'components', ['id'], unique=False)
    op.create_index(op.f('ix_components_machine_model_id'), 'components', ['machine_model_id'], unique=False)
    op.create_index(op.f('ix_components_type'), 'components', ['type'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_model_id', sa.Integer(), nullable=False),
    sa.Column('source_component_id', sa.Integer(), nullable=False),
    sa.Column('target_component_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], ),
    sa.ForeignKeyConstraint(['source_component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['target_component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_connections_machine_model_id'), 'connections', ['machine_model_id'], unique=False)
    op.create_index(op.f('ix_connections_source_component_id'), 'connections', ['source_component_id'], unique=False)
    op.create_index(op.f('ix_connections_target_component_id'), 'connections', ['target_component_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connections_target_component_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_source_component_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_machine_model_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_components_type'), table_name='components')
    op.drop_index(op.f('ix_components_machine_model_id'), table_name='components')
    op.drop_index(op.f('ix_components_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_machine_models_project_id'), table_name='machine_models')
    op.drop_index(op.f('ix_machine_models_name'), table_name='machine_models')
    op.drop_index(op.f('ix_machine_models_id'), table_name='machine_models')
    op.drop_table('machine_models')
    # ### end Alembic commands ###