"""Add communication_bindings table and relationships (corrected)

Revision ID: 6b6b62f02921
Revises: 2c3ee6d2cc73
Create Date: 2025-04-11 15:34:03.238026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6b62f02921'
down_revision: Union[str, None] = '2c3ee6d2cc73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_model_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('component_port', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_bindings_component_id'), 'communication_bindings', ['component_id'], unique=False)
    op.create_index(op.f('ix_communication_bindings_component_port'), 'communication_bindings', ['component_port'], unique=False)
    op.create_index(op.f('ix_communication_bindings_direction'), 'communication_bindings', ['direction'], unique=False)
    op.create_index(op.f('ix_communication_bindings_id'), 'communication_bindings', ['id'], unique=False)
    op.create_index(op.f('ix_communication_bindings_machine_model_id'), 'communication_bindings', ['machine_model_id'], unique=False)
    op.create_index(op.f('ix_communication_bindings_protocol'), 'communication_bindings', ['protocol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communication_bindings_protocol'), table_name='communication_bindings')
    op.drop_index(op.f('ix_communication_bindings_machine_model_id'), table_name='communication_bindings')
    op.drop_index(op.f('ix_communication_bindings_id'), table_name='communication_bindings')
    op.drop_index(op.f('ix_communication_bindings_direction'), table_name='communication_bindings')
    op.drop_index(op.f('ix_communication_bindings_component_port'), table_name='communication_bindings')
    op.drop_index(op.f('ix_communication_bindings_component_id'), table_name='communication_bindings')
    op.drop_table('communication_bindings')
    # ### end Alembic commands ###